name: "Build"

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2
      - name: Builder image
        run: docker build -t elcash-build-github-$GITHUB_ACTION --build-arg GIT_COMMIT=$GITHUB_REF-$GITHUB_SHA -f ci/docker/Dockerfile .
